DROP TABLE AIReview;
DROP TABLE BestBuyReview;
DROP TABLE CartContainsProduct;
DROP TABLE Product;
DROP TABLE Searches;
DROP TABLE Cart;
DROP TABLE User;
DROP TABLE Advertisement;
DROP TABLE UserInterface;